apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient
spec:
  replicas: 3
  selector:
    matchLabels:
      app: patient
  template:
    metadata:
      labels:
        app: patient
    spec:
      containers:
      - name: patient
        image: 014498634556.dkr.ecr.ap-south-1.amazonaws.com/bhrc-patient:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: patient
spec:
  selector:
    app: patient
  ports:
  - port: 80
    targetPort: 5001
  type: ClusterIP
